# Generated by Django 2.1.3 on 2019-03-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoviestats',
            name='lastWatchPos',
            field=models.DurationField(null=True),
        ),
    ]
