# Generated by Django 2.1.3 on 2019-03-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completedTutorial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usermoviestats',
            name='lastRating',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
