# Generated by Django 2.1.3 on 2019-03-13 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190313_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoviestats',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
