# Generated by Django 2.1.3 on 2019-03-14 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190314_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoviestats',
            name='rating',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='usermoviestats',
            name='recommendValue',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
