# Generated by Django 2.1.3 on 2019-02-14 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_favouritegenres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritegenres',
            name='genreId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersfavourite', to='movies.Genres'),
        ),
        migrations.AlterField(
            model_name='favouritegenres',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favouritegenres', to=settings.AUTH_USER_MODEL),
        ),
    ]
