# Generated by Django 2.1.3 on 2019-02-14 20:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movies_releasedate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_auto_20190214_2029'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favouritegenres',
            unique_together={('userId', 'genreId')},
        ),
    ]
