# Generated by Django 2.1.3 on 2019-03-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190313_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoviestats',
            name='lastWatchPos',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
