# Generated by Django 2.1.3 on 2019-03-13 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190313_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermoviestats',
            name='recommendValue',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
