# Generated by Django 2.1.3 on 2019-03-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actorId', models.AutoField(primary_key=True, serialize=False)),
                ('actorFirstName', models.CharField(max_length=100)),
                ('actorLastName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('directorId', models.AutoField(primary_key=True, serialize=False)),
                ('directorFirstName', models.CharField(max_length=100)),
                ('directorLastName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genreId', models.AutoField(primary_key=True, serialize=False)),
                ('genreName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieId', models.AutoField(primary_key=True, serialize=False)),
                ('movieName', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('length', models.DurationField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('trailerLink', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img')),
                ('noRents', models.PositiveIntegerField(blank=True, null=True)),
                ('releaseDate', models.DateField(blank=True, null=True)),
                ('addedDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('overallRating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ageRating', models.CharField(blank=True, max_length=3, null=True)),
                ('actors', models.ManyToManyField(blank=True, related_name='movies', to='movies.Actor')),
                ('directors', models.ManyToManyField(blank=True, related_name='movies', to='movies.Director')),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='movies.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('writerId', models.AutoField(primary_key=True, serialize=False)),
                ('writerFirstName', models.CharField(max_length=100)),
                ('writerLastName', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='writers',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.Writer'),
        ),
    ]
