# Generated by Django 2.1.7 on 2019-03-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRating',
            fields=[
                ('movieId', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField()),
            ],
        ),
    ]
