# Generated by Django 2.1.7 on 2019-03-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movierating'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('ratingId', models.AutoField(primary_key=True, serialize=False)),
                ('movieId_Id', models.PositiveIntegerField()),
                ('rating', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='MovieRating',
        ),
    ]
