# Generated by Django 2.1.7 on 2019-03-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20190307_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='userId_Id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
