# Generated by Django 2.1.3 on 2019-02-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movies_actors2'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movieactors',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='movieactors',
            name='actorId',
        ),
        migrations.RemoveField(
            model_name='movieactors',
            name='movieId',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='actors2',
        ),
        migrations.AddField(
            model_name='movies',
            name='actors',
            field=models.ManyToManyField(to='movies.Actors'),
        ),
        migrations.DeleteModel(
            name='MovieActors',
        ),
    ]
