# Generated by Django 2.1.3 on 2019-02-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20190227_1641'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moviedirectors',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='moviedirectors',
            name='directorId',
        ),
        migrations.RemoveField(
            model_name='moviedirectors',
            name='movieId',
        ),
        migrations.AlterUniqueTogether(
            name='moviegenres',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='moviegenres',
            name='genreId',
        ),
        migrations.RemoveField(
            model_name='moviegenres',
            name='movieId',
        ),
        migrations.AlterUniqueTogether(
            name='moviewriters',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='moviewriters',
            name='movieId',
        ),
        migrations.RemoveField(
            model_name='moviewriters',
            name='writerId',
        ),
        migrations.AddField(
            model_name='movies',
            name='directors',
            field=models.ManyToManyField(to='movies.Directors'),
        ),
        migrations.AddField(
            model_name='movies',
            name='genres',
            field=models.ManyToManyField(to='movies.Genres'),
        ),
        migrations.AddField(
            model_name='movies',
            name='writers',
            field=models.ManyToManyField(to='movies.Writers'),
        ),
        migrations.DeleteModel(
            name='MovieDirectors',
        ),
        migrations.DeleteModel(
            name='MovieGenres',
        ),
        migrations.DeleteModel(
            name='MovieWriters',
        ),
    ]
