# Generated by Django 2.1.3 on 2019-02-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20190227_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='actors',
            field=models.ManyToManyField(null=True, to='movies.Actors'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='addedDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='ageRating',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='directors',
            field=models.ManyToManyField(null=True, to='movies.Directors'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genres',
            field=models.ManyToManyField(null=True, to='movies.Genres'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='noRents',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='overallRating',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='releaseDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='trailerLink',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='writers',
            field=models.ManyToManyField(null=True, to='movies.Writers'),
        ),
    ]
