# Generated by Django 2.1.3 on 2019-02-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20190227_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='actors',
            field=models.ManyToManyField(blank=True, to='movies.Actors'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='ageRating',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='directors',
            field=models.ManyToManyField(blank=True, to='movies.Directors'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genres',
            field=models.ManyToManyField(blank=True, to='movies.Genres'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='length',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='noRents',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='overallRating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='releaseDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='trailerLink',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='writers',
            field=models.ManyToManyField(blank=True, to='movies.Writers'),
        ),
    ]
