# Generated by Django 2.1.3 on 2019-02-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_favouritegenres'),
        ('orders', '0001_initial'),
        ('movies', '0008_auto_20190227_1648'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
    atomic = False